# Generated by Django 6.0.4 on 2026-04-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('retail', 'Retail'), ('restaurant', 'Restaurant'), ('pharmacy', 'Pharmacy'), ('salon', 'Salon'), ('generic', 'Generic')], default='generic', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/logos/')),
                ('address', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
